# Generated by Django 2.2.3 on 2019-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_auto_20190717_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetshop',
            name='image',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
    ]
