# Generated by Django 2.2.3 on 2019-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_sweetshop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetshop',
            name='menu',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AddField(
            model_name='sweetshop',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
