# Generated by Django 2.2.3 on 2019-08-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0004_auto_20190728_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweetshop',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
    ]
