# Generated by Django 2.2.4 on 2019-08-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0005_auto_20190804_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetshop',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
