# Generated by Django 2.2.4 on 2019-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0006_sweetshop_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetshop',
            name='pic1',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AddField(
            model_name='sweetshop',
            name='pic2',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AddField(
            model_name='sweetshop',
            name='pic3',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AddField(
            model_name='sweetshop',
            name='pic4',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AddField(
            model_name='sweetshop',
            name='pic5',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AddField(
            model_name='sweetshop',
            name='pic6',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
    ]
