# Generated by Django 2.2.4 on 2019-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0007_auto_20190810_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweetshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='sweetshop',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='sweetshop',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='sweetshop',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='sweetshop',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='sweetshop',
            name='pic5',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='sweetshop',
            name='pic6',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
    ]
