# Generated by Django 3.0.3 on 2020-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0010_auto_20200418_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetshop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
