# Generated by Django 3.0.3 on 2020-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0011_sweetshop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetshop',
            name='map_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
